Ported (OS, Python) matrix testing
oqc-community/qat pull request #124
Opened 2024-06-27 22:20 UTC by hamidelmaazouz

- Slightly related to python clash raised from https://github.com/oqc-community/qat/issues/120
- Noticed we don't have OS + Python testing step in `main` branch

2024-06-28 09:41 UTC, jfriel-oqc approved these changes

2024-07-01 12:23 UTC, keriksson-rosenqvist requested changes

2024-07-01 14:17 UTC, keriksson-rosenqvist approved these changes
LGTM assuming tests will pass.

2024-08-05 22:56 UTC, jfriel-oqc commented
ported to main already

2024-08-05 22:56 UTC, closed without merging