Fix numerical function parameters
oqc-community/qat pull request #26
Opened 2023-11-28 23:39 UTC by hamidelmaazouz

Some numerical functions in `utilities.py` seem to be instantiated in `evaluate_shape()` with the wrong parameter values. This 1-commit PR fixes the problem.

2023-11-28 23:43 UTC, hamidelmaazouz commented
I have read the Contributor License Agreement and I hereby accept the Terms.

2023-11-29 10:21 UTC, chemix-lunacy requested changes

2023-11-29 10:21 UTC, chemix-lunacy commented on src/QAT/qat/purr/compiler/execution.py
> -        buffer: List[float],
We don't enforce numpy array usage anywhere, the original was correct. Please change back.

2023-11-29 10:21 UTC, chemix-lunacy commented on src/QAT/qat/purr/backends/utilities.py
> -            num_func = GaussianSquare(data.std_dev, data.square_width)
@jfriel-oqc Look good to you?

2023-12-11 11:36 UTC, chemix-lunacy reviewed
Removing my request since it's been dealt with, Jamie has to approve the other changes though.

2024-03-13 10:42 UTC, keriksson-rosenqvist commented
Agree with John. @jfriel-oqc can you verify the changes?

2024-03-25 12:02 UTC, closed without merging