Add readout error mitigation to qat
oqc-community/qat pull request #4
Opened 2023-09-07 21:05 UTC by jfriel-oqc

Adds some simple readout mitigation in the form of full matrix (to become sparse) and a constant overhead linear approximation. M3 to be added once we have a hybrid runtime

same as PR on bitbucket, just ported over

The tests aren't passing for a reason outside this PR, will check that out and create and issue separately

2023-09-08 08:09 UTC, chemix-lunacy requested changes
The return dictionary and regex variable splicing will need to be fixed before this goes in.

2023-10-08 10:54 UTC, hamidelmaazouz requested changes

2023-10-08 10:54 UTC, hamidelmaazouz commented on src/QAT/qat/purr/compiler/execution.py
> +            )
this check can precede earlier processing to raise early (unless need to use `readout_instructions` when supporting multiple registers)

2024-02-13 23:25 UTC, jfriel-oqc commented
Reopening this PR, myself and @jdavid-oqc will address these comments this week

2024-02-19 03:08 UTC, jfriel-oqc commented on src/QAT/qat/purr/compiler/execution.py
> +        readout_instructions = [
yeah, that's true, I thought this was an easier API for execution via internal builder, but agree I think it's easier to execute with config

2024-03-04 18:27 UTC, jfriel-oqc commented
Declining as many changes ported over in https://github.com/oqc-community/qat/pull/70

2024-03-04 18:27 UTC, closed without merging