Remove default value of repetition period from Repeat
oqc-community/qat pull request #81
Opened 2024-03-12 15:52 UTC by keriksson-rosenqvist

2024-03-13 15:22 UTC, jfriel-oqc approved these changes

2024-03-13 16:19 UTC, hamidelmaazouz commented
@bryn-bell This PR is actually duplicate of https://github.com/oqc-community/qat/pull/80. Keep only one of them

2024-03-13 16:19 UTC, hamidelmaazouz requested changes

2024-03-13 16:19 UTC, hamidelmaazouz commented on src/QAT/qat/purr/compiler/instructions.py
> -        self.repetition_period = repetition_period or 100e-6
Are there any tests for this change ?

2024-03-13 16:20 UTC, hamidelmaazouz requested changes
@bryn-bell This PR is actually duplicate of https://github.com/oqc-community/qat/pull/80. Keep only one of them

2024-03-14 11:11 UTC, keriksson-rosenqvist commented
> @bryn-bell This PR is actually duplicate of #80. Keep only one of them

@hamidelmaazouz No these are aiming at `main` and `develop` respectively. They are both required. This is the standard process as discussed.

2024-03-14 16:22 UTC, keriksson-rosenqvist commented on src/QAT/qat/purr/compiler/instructions.py
> -        self.repetition_period = repetition_period or 100e-6
@hamidelmaazouz Tests added

2024-03-15 10:11 UTC, hamidelmaazouz approved these changes

2024-03-15 10:26 UTC, merged