Release/2 0 0
oqc-community/qat pull request #96
Opened 2024-04-02 18:12 UTC by jfriel-oqc

2024-04-02 21:39 UTC, hamidelmaazouz approved these changes

2024-04-03 06:33 UTC, keriksson-rosenqvist requested changes
Only minor comments but blocking so we ensure we make a release of current main before this gets merged.

2024-04-03 06:33 UTC, keriksson-rosenqvist commented on src/tests/files/qasm/qasm2/long.qasm
This is exactly the same as [`long_qasm.qasm`](https://github.com/oqc-community/qat/blob/release/2_0_0/src/tests/files/qasm/qasm2/long_qasm.qasm). Is there a need for the duplication?

2024-04-03 06:33 UTC, keriksson-rosenqvist commented on src/tests/serialised_compiler_config_templates/serialised_default_compiler_config_legacy.json
Duplicate of the `v02` file. We should only have one.

2024-04-03 06:33 UTC, keriksson-rosenqvist commented on src/tests/serialised_compiler_config_templates/serialised_full_compiler_config_legacy.json
Duplicate of the `v02` file. We should only have one.

2024-08-05 14:32 UTC, closed without merging

2024-08-05 14:32 UTC, jfriel-oqc commented
no longer relevant, closing